# Change these first
owner: burgerbibliothek # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://www.burgerbib.ch
  - name: Online-Archivkatalog
    url: https://katalog.burgerbib.ch/detail.aspx?ID=129129
  - name: Archives Quickaccess
    url: https://www.archives-quickaccess.ch/bbb
  - name: Bibliothekskatalog
    url: https://slsp-bsb.primo.exlibrisgroup.com/discovery/search?vid=41SLSP_RBE:VU1

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.burgerbib.ch
  # baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/134627079
  name: Burgerbibliothek Bern Upptime
  # introTitle: "Statusseite der Burgerbibliothek Bern"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
