# Change these first
owner: burgerbibliothek # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://www.burgerbib.ch
  - name: Archivkatalog
    url: https://katalog.burgerbib.ch/detail.aspx?ID=129129
  - name: Archives Quickaccess
    url: https://www.archives-quickaccess.ch/bbb
  - name: Bibliothekskatalog
    url: https://slsp-bsb.primo.exlibrisgroup.com/discovery/search?vid=41SLSP_RBE:VU1

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.burgerbib.ch
  # baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/134627079
  name: Burgerbibliothek Bern Upptime
  # introTitle: "Statusseite der Burgerbibliothek Bern"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
# Translation
i18n:
  activeIncidents: Aktive Ereignisse
  allSystemsOperational: Alle Systeme sind einsatzbereit
  incidentReport: "Bericht Ereignis #$NUMBER →"
  activeIncidentSummary: Eröffnet am $DATE mit Beitrag $POSTS
  incidentTitle: Details zu Ereignis $NUMBER
  incidentDetails: Ereignisdetails
  incidentFixed: Behoben
  incidentOngoing: Laufend
  incidentOpenedAt: Eröffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: Auf GitHub ansehen und abonnieren
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Ereignissen
  pastIncidents: Vergangene Ereignisse
  pastIncidentsResolved: Behoben in $MINUTES Minuten mit Beitrag $POSTS
  liveStatus: Live-Status
  overallUptime: "Insgesamte Betriebszeit: $UPTIME"
  overallUptimeTitle: Insgesamte Betriebszeit
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7-tägige Antwortzeit
  responseTimeMs: Antwortzeit (ms)
  up: Online
  down: Offline
  degraded: Vermindert
  ms: ms
  loading: Am laden
  navGitHub: GitHub
  footer: Diese Seite ist [open source]($REPO), und mit [Upptime](https://upptime.js.org) betrieben.
  rateLimitExceededTitle: Ratenobergrenze überschritten
  rateLimitExceededIntro: Sie haben die Anzahl der Anfragen, die Sie in einer Stunde durchführen können, überschritten, so dass Sie warten müssen, bevor Sie diese Website erneut aufrufen können. Alternativ können Sie ein persönliches GitHub-Zugangs-Token hinzufügen, um diese Website weiterhin nutzen zu können.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Website verwendet die GitHub-API, um Echtzeitdaten über den Status unserer Websites abzurufen. Standardmäßig erlaubt GitHub jeder IP-Adresse 60 Anfragen pro Stunde, die Sie verbraucht haben.
  rateLimitExceededErrorHowCanFix: Wie kann ich das beheben?
  rateLimitExceededErrorFix: Sie können eine weitere Stunde warten und das Limit für Ihre IP-Adresse wird wiederhergestellt. Alternativ können Sie Ihr persönliches GitHub-Zugangs-Token hinzufügen, mit dem Sie zusätzliche 5.000 Anfragen pro Stunde erhalten.
  rateLimitExceededGeneratePAT: Erfahren Sie, wie Sie ein persönliches Zugangstoken erstellen
  rateLimitExceededHasSet: Sie haben ein persönliches Zugangstoken gesetzt.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Kopieren und Einfügen des Token
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Es ist ein Fehler aufgetreten
  errorIntro: Beim Versuch, die neuesten Statusinformationen zu erhalten, ist ein Fehler aufgetreten.
  errorText: Sie können es in wenigen Augenblicken erneut versuchen.
  errorHome: Zur Startseite wechseln
  pastScheduledMaintenance: Vergangene planmässige Wartung
  scheduledMaintenance: Geplante Wartungen
  scheduledMaintenanceSummaryStarted: Begonnen am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Begonnen am
  startsAt: Beginnt am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: alle
